---
- hosts: myservers
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

- name: Initialize master and worker nodes
  hosts: myservers
  tasks:
  - name: disable UFW firewall for labs
    become: yes
    service:
      name: ufw
      state: stopped
      enabled: false

  - name: Allow IPv4 packets to be routed between interfaces
    become: yes
    copy:
      dest: /etc/sysctl.d/k8s.conf
      content: |
        net.ipv4.ip_forward = 1
      owner: root
      group: root
      mode: '0644'

  - name: Apply sysctl parameters without reboot
    command: sysctl --system

  - name: Installation of apt-utils
    become: yes
    apt:
      name: apt-transport-https
      state: present
      update_cache: yes


  - name: Installation of Containerd
    become: yes
    apt:
      name: containerd
      state: present

  - name: Setting value of SystemdCgroup
    become: yes
    shell: |
      mkdir -p /etc/containerd
      containerd config default | sudo tee /etc/containerd/config.toml | grep SystemdCgroup
      sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

  - name : Starting Containerd service
    service:
      name: containerd
      state: started
      enabled: yes

  - name: Create directory for apt keyrings
    become: yes
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Get Kubernetes GPG key
    get_url:
      url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
      dest: /tmp/kubernetes-release.key

  - name: Convert key to dearmored format
    become: yes
    # Ansible 2.12+ ha il modulo community.crypto 
    # (community.crypto.openssl_dhparam, ecc.), ma se non 
    # disponibile, si può usare il modulo command/shell:
    command: >
      gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      /tmp/kubernetes-release.key
    args:
      creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  - name: Add Kubernetes repository
    become: yes
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
      filename: "kubernetes.list"
      state: present

  - name: Update apt cache
    become: yes
    apt:
      update_cache: yes

  - name: Install kubelet and kubeadm
    become: yes
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - kubeadm
      - kubelet

  - name: install kubectl
    become: yes
    apt:
      name: kubectl
      state: present
    #  when: "'masters' in group_names" # TODO

  # Blocking packages to the exact version. Kubernetes has to be
  # updated with special attention
  - name: Hold kubeadm, kubectl, and kubelet packages
    become: yes
    command: apt-mark hold "{{ item }}"
    loop:
      - kubeadm
      - kubectl
      - kubelet
    changed_when: false
