---
- hosts: myservers
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

- name: Initialize master and worker nodes
  hosts: myservers
  tasks:

   - name: disable UFW firewall for labs
     service:
        name: ufw
        state: stopped
        enabled: false
     become: yes

  #- name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
    #sysctl:
      #name: net.bridge.bridge-nf-call-iptables
      #value: '1'
      #state: present
      #reload: yes

   - name: Installation of apt-utils
     become: yes
     apt:
      name: apt-transport-https
      state: present
      update_cache: yes

   - name: Adding Docker GPG key
     become: yes
     ansible.builtin.apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   - name: Adding Docker Repository
     become: yes
     apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
       state: present

   - name: Installation of Docker
     become: yes
     apt:
      name: "{{ item }}"
      state: present
     loop:
       - docker-ce
       - docker-ce-cli
       - containerd.io
       - docker-compose

   - name: Setting value of SystemdCgroup
     become: yes
     shell: |
       containerd config default | sudo tee /etc/containerd/config.toml | grep SystemdCgroup
       sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

   - name : Starting Service of Docker
     service:
       name: docker
       state: started
       enabled: yes

   - name: Create directory for apt keyrings
     become: yes
     ansible.builtin.file:
       path: /etc/apt/keyrings
       state: directory
       mode: '0755'

   - name: Adding Kubernetes GPG key
     become: yes
     ansible.builtin.apt_key:
       url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
       state: present

   - name: Add Kubernetes repository
     become: yes
     ansible.builtin.apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
      state: present

   - name: Update apt cache
     ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600

   - name: Install kubelet and kubeadm
     apt:
        name: "{{ item }}"
        state: present
     loop:
       - kubeadm
       - kubelet

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started

   - name: install kubectl
     apt:
        name: kubectl
        state: present
     when: "'masters' in group_names"

